### ISSUE TITLE
upstream playbooks have moved beyond ansible 1.9.6

### ISSUE THREAD

**Issue by lbragstad** [lbragstad/keystone-performance#21]
At the time of putting all this together, we pinned our ansible version to something **under** ansible 2, per requirements from upstream playbooks. It now looks like ansible version 2.2 is compatible with upstream playbooks and we should follow suit [0].

I noticed this when our performance job failed due to ansible 2.2 requirements and we were running ansible 1.9.6 [1].

[0] https://github.com/openstack/openstack-ansible-galera_client/commit/a7c775302ec092a22118fd3d11ceb19cc2831c4e
[1] http://cdn.pasteraw.com/3un8p5ex1qfqxx9noio82g6dp1yhgnd

**Comment by odyssey4me** [comment]
@lbragstad If you want to monitor for Ansible version changes for the os_keystone role, monitor this file: https://github.com/openstack/openstack-ansible-tests/blob/master/test-ansible-deps.txt

That's the file that will get changed in order to change our Ansible version.
